### PR TITLE
Additional query support part1

### PR DESCRIPTION
**Pull request by Xeinn**
As requested by @Incarnation-p-lee 
First of set of 4 pull requests to introduce additional query method support

### CODE REVIEW

**Comment by Xeinn** [comment]
@Incarnation-p-lee 
Seems to be getting the same error when trying to merge to this branch as was seen when merging to master??

**Comment by Incarnation-p-lee** [comment]
@Xeinn 
Sorry for misleading here, I mean you can just clone this repo(not the forked one). And then create new branch with your code. Then send the PR by this repo instead of the forked one. Sorry for inconvenience.

**Comment by Xeinn** [comment]
Ahh, ok :) sorry misunderstood.  Will give that a go.

Regards

Chris

On 25 Jul 2018 1:55 am, Pan Li <notifications@github.com> wrote:

@Xeinn<https://github.com/Xeinn>
Sorry for misleading here, I mean you can just clone this repo(not the forked one). And then create new branch with your code. Then send the PR by this repo instead of the forked one. Sorry for inconvenience.

**Comment by sophiaso** [comment]
Closed as feature has been merged in other PRs.

**Pull request closed without merging**
