### PR TITLE
Additional query criteria support - part 1

### PR DESCRIPTION
**Pull request by Xeinn**
As per previous discussions re. pull request #72 this pull request contains initial preparatory changes for the support of additional method name based query selection criteria.

The PR introduces the the new Criteria and Query classes - temporarily named NewCriteria and New Query along with unit tests for both.  Additionally a CriteriaType enumeration is introduced providing identifiers for the different types of criteria that can be specified by a repository method name.

### CODE REVIEW

**Comment by Xeinn** [comment]
@Incarnation-p-lee - not sure what I may have done wrong here, have added the initial files as suggested but this seems to have broken CI tests?

**Comment by Incarnation-p-lee** [comment]
@Xeinn 
Thanks for your PRs, it looks nice, and more clear than before. For some minor enhancement for you code, as well as make `IT` test pass.
Thanks for you great work again. 👍

**Comment by Xeinn** [comment]
@Incarnation-p-lee 
Thanks for the feedback, two small commits made with adjustments.  However I'm not sure these are the cause of the IT tests not passing there seems to be some issue in the logs with the DBKey - reported from line 70 of DocumenrDBTemplateIT (masterKey)

`[INFO] Initializing DocumentClient with serviceEndpoint [], ConnectionPolicy [ConnectionPolicy [requestTimeout=60, mediaRequestTimeout=300, connectionMode=Gateway, mediaReadMode=Buffered, maxPoolSize=100, idleConnectionTimeout=60, userAgentSuffix=, retryOptions=com.microsoft.azure.documentdb.RetryOptions@673be18f, enableEndpointDiscovery=true, preferredLocations=null]], ConsistencyLevel [Session]
  java.lang.IllegalArgumentException(masterKey)
  java.lang.NullPointerException(null), mergedContextConfiguration = [MergedContextConfiguration@35047d03 testClass = DocumentDbTemplateIT, locations = '{}', classes = '{}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{}', contextCustomizers = set[org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@7fe8ea47, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@255b53dc, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@5b0abc94], contextLoader = 'org.springframework.test.context.support.DelegatingSmartContextLoader', parent = [null]]], class annotated with @DirtiesContext [false] with mode [null], method annotated with @DirtiesContext [false] with mode [null].`

**Comment by Incarnation-p-lee** [comment]
@Xeinn 
It seems all IT test are failed. You can pick one randomly to figure out why.

`Tests run: 35, Failures: 0, Errors: 35, Skipped: 0`

And for example:

`
  AddressRepositoryIT.canDeleteByIdAndPartitionedCity » IllegalState Failed to l...
  AddressRepositoryIT.canDeleteByPartitionedCity » IllegalState Failed to load A...
  AddressRepositoryIT.deleteWithoutPartitionedColumnShouldFail » IllegalState Fa...
  AddressRepositoryIT.testCount » IllegalState Failed to load ApplicationContext
  AddressRepositoryIT.testFindAll » IllegalState Failed to load ApplicationConte...
  AddressRepositoryIT.testFindByIdForPartitionedCollection » IllegalState Failed...
  AddressRepositoryIT.testFindByPartitionedCity » IllegalState Failed to load Ap...
  AddressRepositoryIT.testUpdateEntity » IllegalState Failed to load Application...
  ContactRepositoryIT.testBatchOperations » IllegalState Failed to load Applicat...
  ContactRepositoryIT.testCountAndDeleteByID » IllegalState Failed to load Appli...
  ContactRepositoryIT.testCountAndDeleteEntity » IllegalState Failed to load App...
  ContactRepositoryIT.testCustomQuery » IllegalState Failed to load ApplicationC...
  ContactRepositoryIT.testFindAll » IllegalState Failed to load ApplicationConte...
  ContactRepositoryIT.testFindById » IllegalState Failed to load ApplicationCont...
  ContactRepositoryIT.testNullIdContact » IllegalState Failed to load Applicatio...
  ContactRepositoryIT.testUpdateEntity » IllegalState Failed to load Application...
`

**Comment by Xeinn** [comment]
@Incarnation-p-lee 

All of the IT tests are failing for the same reason.  Not being able to load the ApplicationContext due to an invalid argument for masterKey (which i suspect is null).

All IT tests are running fine for me locally against the emulator and the pull request only adds files that aren't in the control path for any of the IT tests.

I created a separate pull request PR #136, based on the current master, which only introduces the CriteriaType enum with no other changes.

This too fails with the same IT errors so I suspect this is not something to do with the code in the pull request.

Appreciate the help so far guys but running short on the time I can commit to this... will try to revisit again next week.

**Comment by Incarnation-p-lee** [comment]
@Xeinn 
Thanks for you great work. I will check that on travis CI and figure out what happens.

**Comment by Incarnation-p-lee** [comment]
@Xeinn 
I see, the travis CI forbidden the access from forked repo to touch secret variable. See below:

**The most important restriction for pull requests is about secure environment variables and encrypted data.
A pull request sent from a fork of the upstream repository could be manipulated to expose environment variables. The upstream repository’s maintainer would have no protection against this attack, as pull requests can be sent by anyone who forks the repository on GitHub.**

So could you please create PR from you repo to another branch excluding master, like development branch. And I can create the PR to master on be half of you ?
Sorry for inconvenient, and thanks again for you great work.

**Comment by Incarnation-p-lee** [comment]
@Xeinn 
I create one new branch named `development`, could you please send PR to that branch ? Sorry for inconvenience.

**Comment by Incarnation-p-lee** [comment]
@Xeinn 
I added the write authentication to you of this repo. Could you please clone this repo, and resend the PR based on that ? Thanks a lot.

**Comment by Xeinn** [comment]
Hi,

Thanks Pan Li, will take a look though it may not be until next week as I'm away from home at the moment.

Many thanks

Chris

On 28 Jun 2018 4:36 am, Pan Li <notifications@github.com> wrote:

@Xeinn<https://github.com/Xeinn>
I added the write authentication to you of this repo. Could you please clone this repo, and resend the PR based on that ? Thanks a lot.

**Comment by Incarnation-p-lee** [comment]
@Xeinn 
Hi, Can you access this repo directly with PRs ? Any problem please fell free to contact me. ;)

**Comment by Xeinn** [comment]
Closing pull request to re-submit to development branch created by @Incarnation-p-lee

**Pull request closed without merging**
