### PR TITLE
CosmosException when using azure-spring-data-cosmos query methods with repeated parameters

### PR DESCRIPTION
**Pull request by dsibilio**
Backporting the [PR](https://github.com/Azure/azure-sdk-for-java/pull/17962) that solved the [same issue](https://github.com/Azure/azure-sdk-for-java/issues/17961) for the azure-spring-data-cosmos library.

### CODE REVIEW

**Comment by kushagraThapar** [comment]
Regarding this PR, we are not actively managing this branch anymore, is there a reason you need it for spring-data-cosmos v2 SDK ?

**Comment by dsibilio** [comment]
Some projects I work on couldn't be migrated yet to the newer azure-spring-data-cosmos library, therefore it would have been handy for me to have this fix backported to a 2.3.1

If there is no chance of getting any new releases/patches from this repo then feel free to close the PR.

**Comment by kushagraThapar** [comment]
I see, I would strongly recommend to migrate to newer version of azure-spring-data-cosmos library. 
However, if you are having issues in production because of this bug, I can see if we can make an exception to release hotfix for this module. Let me know.

**Comment by dsibilio** [comment]
It's not critical to me at the moment, and we definitely plan on upgrading to the newest library as soon as possible.
Thank you for being available to help, in case things may change I'll post it here.

**Comment by kushagraThapar** [comment]
Sounds good, let me know and we can ship it.

**Comment by dsibilio** [comment]
Closing this PR as it's obsolete 🙏

**Pull request closed without merging**
